[project]
name = "image-process"
version = "1.0.1"
dependencies = [
  "pillow==12.0.0",
  "pillow-avif-plugin==1.5.2",
  "pillow-heif==1.1.1"
]

[project.optional-dependencies]
dev = [
  "pyinstaller==6.16.0",  
]
